config/routes.rb
Rails.application.routes.draw do
  root to: "datastreams#index"
  resources :datastreams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tanda.rb
class Tanda
  def initialize(token)
    @token = token
    @base_url = "https://my.tanda.co/api/v2/"
    @auth = "Bearer " + @token
    @headers = {"Cache-Control"=> "no-cache", "Authorization"=> @auth}
  end

  def get_datastreams
    get("datastreams", @token)
  end

  def get_datastream(id)
    get("datastreams/#{id}", @token)
  end

  def create_datastream(body)
    post("datastreams", body)
  end

  def update_datastream(id, body)
    put("datastreams/#{id}", body)
  end

  def delete_datastream(id)
    delete("datastreams/#{id}")
  end

  private

  def post(extention, body)
    HTTParty.post(@base_url + extention, :headers => @headers, :query => body)
  end

  def get(extension, token)
    HTTParty.get(@base_url + extension, :headers => @headers).parsed_response
  end

  def put(extention, body)
    HTTParty.put(@base_url + extention, :headers => @headers, :query => body)
  end

  def delete(extension)
    HTTParty.delete(@base_url + extension, :headers => @headers)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/datastreams_controller.rb
class DatastreamsController < ApplicationController
  before_action :initialize_tanda_client

  def index
    @datastreams = @client.get_datastreams.map { |d| d.symbolize_keys }
  end

  def new
    @intervals = [
      ['1 day', 86400],
      ['1 hr', 3600],
      ['30 min', 1800],
      ['15 min', 900]
    ]
  end

  def create
    datastream = @client.create_datastream(build_payload)
    redirect_to datastreams_path
  end

  def destroy
    response = @client.delete_datastream(params[:id])
    flash[:info] = "Datastream is queued for deletion. It may take a while."
    redirect_to datastreams_path
  end

  private

  def initialize_tanda_client
    @client = Tanda.new("6cd1d12d43a44322a381899f6b4d2e5cdd0e4ba8bc723463f0e1bac870862257")
  end

  def build_payload
    { 
      name: params[:name],
      data_interval: params[:interval]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datastreams_helper.rb
module DatastreamsHelper
end

app/views/datastreams/index.html.erb
<div class="container">
  <div class="columns">
    <div class="column">
      <%= link_to "New datastream", new_datastream_path, class: "button is-info" %>
      <table class="table is-narrow is-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Source</th>
            <th>Data interval</th>
            <th>Enabled</th>
            <th>Print mode</th>
            <th>Roster display mode</th>
            <th>Updated at</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @datastreams.each do |datastream| %>
            <tr>
              <td><%= datastream[:id] %></td>
              <td><%= datastream[:name] %></td>
              <td><%= datastream[:source] %></td>
              <td><%= datastream[:data_interval] %></td>
              <td><%= datastream[:enabled] %></td>
              <td><%= datastream[:print_mode] %></td>
              <td><%= datastream[:roster_display_mode] %></td>
              <td><%= Time.at(datastream[:updated_at]).to_datetime.strftime("%b %-d %Y, %H:%M") %></td>
              <td>
                <%= link_to datastream_path(datastream), method: :delete, data: { confirm: "Delete?" } do %>
                  <span class="icon is-small"><i class="fa fa-minus-circle"></i></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/datastreams/new.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-half is-offset-one-quarter">
      <%= form_tag controller: "datastreams", action: "create", method: "post" do %>
        <div class="field">
          <label class="label">Name:</label>
          <p class="control">
            <%= text_field_tag :name, nil, class: "input" %>
          </p>
        </div>

        <div class="field">
          <label class="label">Interval:</label>
          <p class="control">
            <span class="select">
              <%= select_tag(:interval, options_for_select(@intervals)) %>
            </span>
          </p>
        </div>

        <div class="field is-grouped">
          <p class="control">
            <%= submit_tag "Create datastream", class: "button is-info" %>
          </p>
          <p class="control">
            <button class="button is-link">Cancel</button>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TandaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="has-text-centered is-#{key}"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>